name: CI

# Note: this action won't run properly unless secrets are setup

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: haxe -version
      - run: haxelib install --always game-js.hxml
      - run: haxe game-js.hxml
      # You could upload the output to S3 for example using jakejarvis/s3-sync-action

  android:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Enable Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - 
        name: Execute Docker build
        uses: docker/build-push-action@v2
        with:
          target: upload-to-play
          context: . # This is needed because this action will otherwise checkout a new separate repo (without LFS)
                     # https://stackoverflow.com/questions/66303185/docker-copy-fails-github-actions-with-git-lfs
          secrets: |
            "keystore-base64=${{ secrets.ANDROID_KEYSTORE }}"
            "keystore-password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
            "service-account=${{ secrets.PLAY_SERVICE_ACCOUNT }}"
